image: docker:stable
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:18.09-dind

stages:
  - build
  - deploy

.build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker pull $IMAGE || true
    - docker build -t $IMAGE .
    - docker push $IMAGE

build-dev:
  extends: .build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:latest
  only:
    - development

build-prod:
  extends: .build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:stable
  only:
    - master

deploy:
  stage: deploy
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:stable
    IMAGE_NAME: itrainyoufrontend
    SERVER_IP: 109.71.10.78
    USER: 'django'
  script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$PRODUCTION_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 $USER@$SERVER_IP "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} registry.gitlab.com"
    - ssh -p22 $USER@$SERVER_IP "docker pull ${IMAGE_TAG}"
    - ssh -p22 $USER@$SERVER_IP "docker rm -f ${IMAGE_NAME} || true"
    - ssh -p22 $USER@$SERVER_IP "docker run --network=itrainyou-backend_default --name ${IMAGE_NAME} -e BACKEND_URL=https://backend.itrainyou.ru -e WS_HOST=wss://backend.itrainyou.ru -e AGORA_ID=ddc00001a79048e98fc21cfeef7efa7c -e SENTRY_CLIENT_DSN=https://f6205d3153964e93afabe2313b1b2ab3@o474760.ingest.sentry.io/5511546 -e SENTRY_SERVER_DSN=https://b359770ce05a40ab86c17dd35faf34c1@o474760.ingest.sentry.io/5514727 -e FACEBOOK_CLIENT_ID=588161764971621 -e VK_CLIENT_ID=7636787 -e GOOGLE_CLIENT_ID=536974560462-812pv0n2s063m7keq9eiluqve3lfelf1.apps.googleusercontent.com -e SERVER_TYPE=production -e PORT=3000  --restart unless-stopped -d ${IMAGE_TAG}"
    - ssh -p22 $USER@$SERVER_IP "docker logout registry.gitlab.com"
  only:
    - master
