export const timeZones = [
  { label: "(GMT-12: 00) Международная линия дат Запад", value: "Etc/GMT+12" },
  { label: "(GMT-11: 00) Мидуэй, Самоа", value: "Pacific/Midway" },
  { label: "(GMT-10: 00) Гавайи", value: "Pacific/Honolulu" },
  { label: "(GMT-08: 00) Аляска", value: "America/Juneau" },
  { label: "(GMT-07: 00) Тихоокеанское время (США и Канада); Тихуана", value: "America/Dawson" },
  { label: "(GMT-07: 00) Аризона", value: "America/Phoenix" },
  { label: "(GMT-06: 00) Центральная Америка", value: "America/Belize" },
  { label: "(GMT-06: 00) Горное время (США и Канада)", value: "America/Boise" },
  { label: "(GMT-06: 00) Чихуахуа, Ла-Пас, Масатлан", value: "America/Chihuahua" },
  { label: "(GMT-06: 00) Саскачеван", value: "America/Regina" },
  { label: "(GMT-05: 00) Богота, Лима, Кито", value: "America/Bogota" },
  { label: "(GMT-05: 00) Центральное время (США и Канада)", value: "America/Chicago" },
  { label: "(GMT-05: 00) Гвадалахара, Мехико, Монтеррей", value: "America/Mexico_City" },
  { label: "(GMT-04: 00) Каракас, Ла-Пас", value: "America/Caracas" },
  { label: "(GMT-04: 00) Восточное время (США и Канада)", value: "America/Detroit" },
  { label: "(GMT-04: 00) Индиана (Восток)", value: "America/Indiana/Indianapolis" },
  { label: "(GMT-04: 00) Сантьяго", value: "America/Santiago" },
  { label: "(GMT-03: 00) Буэнос-Айрес, Джорджтаун", value: "America/Argentina/Buenos_Aires" },
  { label: "(GMT-03: 00) Атлантическое время (Канада)", value: "America/Glace_Bay" },
  { label: "(GMT-03: 00) Бразилиа", value: "America/Sao_Paulo" },
  { label: "(GMT-02: 30) Ньюфаундленд и Лабрадор", value: "America/St_Johns" },
  { label: "(GMT-02: 00) Гренландия", value: "America/Godthab" },
  { label: "(GMT-02: 00) Средняя Атлантика", value: "Etc/GMT+2" },
  { label: "(GMT-01: 00) острова Кабо-Верде", value: "Atlantic/Cape_Verde" },
  { label: "(GMT) Азорские острова", value: "Atlantic/Azores" },
  { label: "(GMT) Дублин, Эдинбург, Лиссабон, Лондон", value: "GMT" },
  { label: "(GMT + 01: 00) Западная Центральная Африка", value: "Africa/Algiers" },
  { label: "(GMT + 01: 00) Касабланка, Монровия", value: "Africa/Casablanca" },
  { label: "(GMT + 01: 00) Канарские острова", value: "Atlantic/Canary" },
  { label: "(GMT + 02: 00) Каир", value: "Africa/Cairo" },
  { label: "(GMT + 02: 00) Хараре, Претория", value: "Africa/Harare" },
  { label: "(GMT + 02: 00) Амстердам, Берлин, Берн, Рим, Стокгольм, Вена", value: "Europe/Amsterdam" },
  { label: "(GMT + 02: 00) Белград, Братислава, Будапешт, Любляна, Прага", value: "Europe/Belgrade" },
  { label: "(GMT + 02: 00) Брюссель, Копенгаген, Мадрид, Париж", value: "Europe/Brussels" },
  { label: "(GMT + 02: 00) Сараево, Скопье, Варшава, Загреб", value: "Europe/Sarajevo" },
  { label: "(GMT + 03: 00) Найроби", value: "Africa/Nairobi" },
  { label: "(GMT + 03: 00) Багдад", value: "Asia/Baghdad" },
  { label: "(GMT + 03: 00) Иерусалим", value: "Asia/Jerusalem" },
  { label: "(GMT + 03: 00) Кувейт, Эр-Рияд", value: "Asia/Kuwait" },
  { label: "(GMT + 03: 00) Афины, Стамбул, Минск", value: "Europe/Athens" },
  { label: "(GMT + 03: 00) Бухарест", value: "Europe/Bucharest" },
  { label: "(GMT + 03: 00) Хельсинки, Киев, Рига, София, Таллин, Вильнюс", value: "Europe/Helsinki" },
  { label: "(GMT + 03: 00) Москва, Санкт-Петербург, Волгоград", value: "Europe/Moscow" },
  { label: "(GMT + 04: 00) Баку, Тбилиси, Ереван", value: "Asia/Baku" },
  { label: "(GMT + 04: 00) Абу-Даби, Маскат", value: "Asia/Dubai" },
  { label: "(GMT + 04: 30) Кабул", value: "Asia/Kabul" },
  { label: "(GMT + 04: 30) Тегеран", value: "Asia/Tehran" },
  { label: "(GMT + 05: 00) Исламабад, Карачи, Ташкент", value: "Asia/Karachi" },
  { label: "(GMT + 05: 00) Екатеринбург", value: "Asia/Yekaterinburg" },
  { label: "(GMT + 05: 30) Шри Джаяварденепура", value: "Asia/Colombo" },
  { label: "(GMT + 05: 30) Ченнаи, Калькутта, Мумбаи, Нью-Дели", value: "Asia/Kolkata" },
  { label: "(GMT + 05: 45) Катманду", value: "Asia/Kathmandu" },
  { label: "(GMT + 06: 00) Алматы, Новосибирск", value: "Asia/Almaty" },
  { label: "(GMT + 06: 00) Астана, Дакка", value: "Asia/Dhaka" },
  { label: "(GMT + 06: 30) Янгон Рангун", value: "Asia/Rangoon" },
  { label: "(GMT + 07: 00) Бангкок, Ханой, Джакарта", value: "Asia/Bangkok" },
  { label: "(GMT + 07: 00) Красноярск", value: "Asia/Krasnoyarsk" },
  { label: "(GMT + 08: 00) Иркутск, Улан-Батор", value: "Asia/Irkutsk" },
  { label: "(GMT + 08: 00) Куала-Лумпур, Сингапур", value: "Asia/Kuala_Lumpur" },
  { label: "(GMT + 08: 00) Пекин, Чунцин, САР Гонконг, Урумчи", value: "Asia/Shanghai" },
  { label: "(GMT + 08: 00) Тайбэй", value: "Asia/Taipei" },
  { label: "(GMT + 08: 00) Перт", value: "Australia/Perth" },
  { label: "(GMT + 09: 00) Сеул", value: "Asia/Seoul" },
  { label: "(GMT + 09: 00) Осака, Саппоро, Токио", value: "Asia/Tokyo" },
  { label: "(GMT + 09: 00) Якутск", value: "Asia/Yakutsk" },
  { label: "(GMT + 09: 30) Аделаида", value: "Australia/Adelaide" },
  { label: "(GMT + 09: 30) Дарвин", value: "Australia/Darwin" },
  { label: "(GMT + 10: 00) Владивосток", value: "Asia/Vladivostok" },
  { label: "(GMT + 10: 00) Брисбен", value: "Australia/Brisbane" },
  { label: "(GMT + 10: 00) Хобарт", value: "Australia/Hobart" },
  { label: "(GMT + 10: 00) Канберра, Мельбурн, Сидней", value: "Australia/Sydney" },
  { label: "(GMT + 10: 00) Гуам, Порт-Морсби", value: "Pacific/Guam" },
  { label: "(GMT + 11: 00) Магадан, Соломоновы Острова, Новая Каледония", value: "Asia/Magadan" },
  { label: "(GMT + 12: 00) Окленд, Веллингтон", value: "Pacific/Auckland" },
  { label: "(GMT + 12: 00) острова Фиджи, Камчатка, Маршалловы острова", value: "Pacific/Fiji" },
  { label: "(GMT + 13: 00) Нукуалофа", value: "Pacific/Tongatapu" }
]
